name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - main

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - uses: strongo/go-ci-action@v1.0.2
