on: [push, pull_request]
name: Build

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: go get
      run: go get

    - name: go build ./...
      run: go build ./...

    - name: go vet ./...
      run: go vet ./...

    - name: Test
      run: go test ./...
