name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - '**'

jobs:

  standard_go_workflow:
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
